### ISSUE TITLE
Train HPAL on different Scenarios

### ISSUE THREAD

**Issue by lutfia95** [SmiletoE/HPAL#1]
Hey @SmiletoE, 

thanks for providing HPAL! I have several labeled datasets, such as a solid desk. All datasets contain similar labeled objects with the same labels. So each object has about 17 labels. Can I actually train HPALon such a scenario.? for example to segment the objects or is HPAL specialized for indoor structures?

Best,
Ahmad

**Comment by SmiletoE** [comment]
Hi @lutfia95,
Thanks for your interest! Unfortunately, I have not tried a dataset similar to what you described. If our approach does not work for your dataset, sorry for such inconvenience.

**Comment by lutfia95** [comment]
Hey, I will give it a try and let you know. 

Best, 
Ahmad
