### ISSUE TITLE
compile of nearest_neighbors

### ISSUE THREAD

**Issue by ziwenjie** [SmiletoE/HPAL#3]
Hi:
When I run "sh compile_op.sh," I found that during the compilation of the nearest_neighbors stage, the error 
```gcc: error: knn.cxx: No such file or directory" occurs. ```
![image](https://github.com/SmiletoE/HPAL/assets/49607231/e0a0977d-7d6f-4cb2-bdca-ec8c949c4b81)

After renaming knn_.cxx to knn.cxx and modifying setup.py, a new error appears during compilation: 
```knn.cxx:(.text+0xf390): multiple definition of `cpp_knn.```
![Screenshot from 2023-11-08 07-34-59](https://github.com/SmiletoE/HPAL/assets/49607231/c7654dc3-6cd3-46de-8828-4d5e3ec209f7)

**Comment by Stay-Naive** [comment]
Hi, I got the same problem with you. How did you solve that? @ziwenjie

**Comment by pyarelalchauhan** [comment]
I am too getting the same error. How to solve it @SmiletoE ?

**Comment by WhateverMO** [comment]
@ziwenjie @Stay-Naive @pyarelalchauhan i sloved it!
you can uninstall Cython, and then install Cython==0.29
and rm -rf the build files
sh compile_op.sh
it will be solve
