### ISSUE TITLE
Hello, I used gpu No.5 during training. I changed the gpu number in config.py and the cuda number of pytorch_device in base_agent.py, but the running error is as follows. Do you have any good suggestions?

### ISSUE THREAD

**Issue by xd-429** [SmiletoE/HPAL#8]
![image](https://github.com/SmiletoE/HPAL/assets/83168242/4cc0a13d-58d5-4fdc-b3ac-ec2488d34de7)

**Comment by SmiletoE** [comment]
Hello, you only need to change the GPU number in the config.py and keep the pytorch_device in base_agent.py default.
